### ISSUE TITLE
Does this library use any hardware AES acceleration?

### ISSUE THREAD

**Issue by hongfeiyang** [bcgit/pc-dart#87]
Modern CPUs have AES engine built within their processors, starting from Apple A9 and SnapDragon 805 the compiler is able to emit AES instructions when compiling code that uses AES operations. I just want to know can this library use any hardware acceleration when doing cryptographic operations?
If it doesn't, can you recommend any means for me to use hardware AES accelerations in flutter?

**Comment by untp** [comment]
This package is pure Dart, completely software implementation, so it is slow. If you want to use the device's hardware, you can look into [CryptoKit](https://developer.apple.com/documentation/cryptokit) (iOS) and [Cipher](https://developer.android.com/reference/javax/crypto/Cipher) (android). You need to [write custom platform-specific code](https://flutter.dev/docs/development/platform-integration/platform-channels) for calling APIs from android and iOS.

There is also a flutter [package](https://pub.dev/packages/flutter_sodium) that wraps [libsodium](https://doc.libsodium.org/). It should be faster than this library, because it is written in C.

**Comment by AKushWarrior** [comment]
Yeah, this is not a performance intensive library. Granted, it probably won't be your bottleneck, but you should use flutter-sodium if you absolutely need the fastest performance.

**Comment by writethesky** [comment]
It is very poor in real-time encryption and decryption of video streams and large files, encryption and decryption of ordinary files do not feel. At present, it is used for RSA encryption and decryption. AES uses cryptography, Performance doubled, but still used more CPU on MacOS

**Comment by mwcw** [comment]
> It is very poor in real-time encryption and decryption of video streams and large files, encryption and decryption of ordinary files do not feel. At present, it is used for RSA encryption and decryption. AES uses cryptography, Performance doubled, but still used more CPU on MacOS

No it does not use any hardware acceleration it is a pure dart implementation.
